Repository Azer0s/Olymp, pull requests merged in 2019-01, with the labels that each got.

#7 Refactor code
  Olymp.Communication.Messages/AddUserMessage.cs
  Olymp.Communication.Messages/DistributeMessage.cs
  Olymp.Communication.Messages/GetStatusMessage.cs
  Olymp.Communication.Messages/IMessage.cs
  Olymp.Communication.Messages/Olymp.Communication.Messages.csproj
  Olymp.Communication.Messages/PutMessage.cs
  Olymp.Communication.Messages/SingleValueMessage.cs
  Olymp.Communication/Message.cs
  Olymp.Communication/NodeCommunicationClient.cs
  Olymp.Communication/NodeCommunicationServer.cs
  Olymp.Communication/Olymp.Communication.csproj
  Olymp.Nodes/Abstractions/IService.cs
  Olymp.Nodes/Configuration/ConfigurationTool.cs
  Olymp.Nodes/Master/ConfigurationServerNode.cs
  Olymp.Nodes/Master/MasterNode.cs
  Olymp.Nodes/Node.cs
  Olymp.Persistence/FileRepository.cs
  Olymp.Persistence/StoreContext.cs
  Olymp.Persistence/User.cs
  Olymp.Persistence/UserRepository.cs
  Olymp.Util/Configuration.cs
  Olymp.Util/ConfigurationManager.cs
  Olymp.Util/Extension/ByteArrayExtension.cs
  Olymp.Util/RijndaelManager.cs
  Olymp/LocalUserStore.db
  Olymp/Olymp.csproj
  Olymp/Program.cs
  Olymp/Startup.cs
Labels: refactor

#10 Feature/refactor
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .travis.yml
  Olymp.Communication.Messages/Olymp.Communication.Messages.csproj
  Olymp.Communication.Messages/PutMessage.cs
  Olymp.Communication/NodeCommunicationClient.cs
  Olymp.Communication/NodeCommunicationServer.cs
  Olymp.Communication/Olymp.Communication.csproj
  Olymp.Exceptions/DecryptionFailedException.cs
  Olymp.Exceptions/FileExistsException.cs
  Olymp.Exceptions/InvalidIpException.cs
  Olymp.Exceptions/MissingValueException.cs
  Olymp.Exceptions/UnknownArgumentException.cs
  Olymp.Exceptions/UnknownUserException.cs
  Olymp.Nodes/Configuration/ConfigurationTool.cs
  Olymp.Nodes/Master/ConfigurationServerNode.cs
  Olymp.Nodes/Master/MasterNode.cs
  Olymp.Nodes/Node.cs
  Olymp.Persistence/FileRepository.cs
  Olymp.Persistence/User.cs
  Olymp.Persistence/UserRepository.cs
  Olymp.Util/Configuration.cs
  Olymp.Util/ConfigurationManager.cs
  Olymp.Util/FileHelper.cs
  Olymp.Util/Log.cs
  Olymp.Util/MD5Helper.cs
  Olymp.Util/RijndaelManager.cs
  Olymp/Program.cs
  Olymp/Startup.cs
  PULL_REQUEST_TEMPLATE.md
Labels: aviation, enhancement

#17 Feature/configuration tool
  Olymp.Communication.Messages/AddUserMessage.cs
  Olymp.Communication.Messages/EmptyMessage.cs
  Olymp.Communication.Messages/PutMessage.cs
  Olymp.Communication.Messages/SetUserLevelMessage.cs
  Olymp.Communication/Message.cs
  Olymp.Communication/NodeCommunicationServer.cs
  Olymp.Nodes/Configuration/ConfigurationTool.cs
  Olymp.Nodes/Master/ConfigurationServerNode.cs
  Olymp.Persistence/User.cs
  Olymp.Persistence/UserRepository.cs
  Olymp.Util/FileHelper.cs
  Olymp.Util/RijndaelManager.cs
  Olymp/LocalUserStore.db
Labels: enhancement

#22 Add option to manually set address
  Olymp.Communication/NodeCommunicationClient.cs
  Olymp.Nodes/Configuration/ConfigurationTool.cs
  Olymp.Nodes/Node.cs
  Olymp.Util/Configuration.cs
  Olymp.Util/ConfigurationManager.cs
Labels: enhancement, refactor

#28 Message renamed
  Olymp.Communication/BaseMessage.cs
  Olymp.Communication/NodeCommunicationClient.cs
  Olymp.Communication/NodeCommunicationServer.cs
  Olymp.Nodes/Child/ChildNode.cs
  Olymp.Nodes/Master/ConfigurationServerNode.cs
  Olymp.Nodes/Master/MasterNode.cs
  Olymp.Nodes/Node.cs
  README.md
Labels: refactor
